//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentAtThePoint
    {
        public string EATP_ID { get; set; }
        public string PointID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime DateOfInstallation { get; set; }
    
        public virtual ConnectionPoint ConnectionPoint { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
