//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet
{
    using System;
    using System.Collections.Generic;
    
    public partial class HardwarePorts
    {
        public int RecordOfPort { get; set; }
        public string SerialNumber { get; set; }
        public int Port { get; set; }
        public string TypeOfPort { get; set; }
        public string Login { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual User User { get; set; }
    }
}
